<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MigrateFromSqlToCosmosDb.Domain\MigrateFromSqlToCosmosDb.Domain.csproj" />
    <ProjectReference Include="..\MigrateFromSqlToCosmosDb.Contracts\MigrateFromSqlToCosmosDb.Contracts.csproj" />
  </ItemGroup>

</Project>
